run:
  go: "1.22"
  concurrency: 4
  timeout: 10m

linters:
  disable-all: true
  enable:
    # linters maintained by golang.org
    - gofmt
    - goimports
    - govet
    # linters default enabled by golangci-lint .
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # other linters supported by golangci-lint.
    - gocyclo
    - gosec
    - misspell
    - whitespace
    - revive

linters-settings:
  gocyclo:
    # minimal cyclomatic complexity to report
    min-complexity: 15
  revive:
    rules:
      # Disable if-return as it is too strict and not always useful.
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#if-return
      - name: if-return
        disabled: true
